### ISSUE TITLE
怎么双语

### ISSUE THREAD

**Issue by littleju777** [yinan-c/alfred-translate-it#2]
thank you for your amazing work! 

我还是看不懂怎么设置双语。。。要疯了
<img width="697" alt="image" src="https://github.com/user-attachments/assets/049aac89-7fad-4d55-a0c8-b411ed919678">
<img width="861" alt="image" src="https://github.com/user-attachments/assets/bf7e06f7-8b7a-4a17-923f-748ca42e098c">

**Comment by yinan-c** [comment]
Target Language 是语言1， Base Language 是语言2，确保这两个设置成不一样的，你这里 Google 的  Target 和 Base 都是 Chinese。

**Comment by littleju777** [comment]
Thanks!
