### ISSUE TITLE
翻译实效

### ISSUE THREAD

**Issue by Aerdax** [yinan-c/alfred-translate-it#4]
大佬，翻译突然不好使了，keyword后跟内容不跳出翻译内容了，使用的版本是v1.4.1
现象
<img width="756" alt="image" src="https://github.com/user-attachments/assets/cbec859f-d2cd-447c-b051-4ea7496188d7">
配置如下
<img width="1088" alt="image" src="https://github.com/user-attachments/assets/8c6fa1df-5902-4476-9c96-61d7a056ef33">

**Comment by yinan-c** [comment]
怀疑是 python 环境的问题，可以看一下 debug session(右上角小虫的图标) 吗？

**Comment by yinan-c** [comment]
如果是环境问题，之前版本能用的话，也可以退回1.4，1.4.1 就是加了一个 python 路径

**Comment by Aerdax** [comment]
确实是python问题
<img width="854" alt="image" src="https://github.com/user-attachments/assets/9359f264-26eb-4bfc-9fa1-1c745af37973">
<img width="835" alt="image" src="https://github.com/user-attachments/assets/d28ccff6-2b7e-400a-b1f6-8c8d5dfe498a">
需要升级系统python版本吗

**Comment by Aerdax** [comment]
安装提示已是最新版了耶
<img width="590" alt="image" src="https://github.com/user-attachments/assets/f5e1fded-205e-4295-bfc9-aa7c7847d379">

**Comment by yinan-c** [comment]
Homebrew 的 Python 之前确实有点问题 （可能是因为版本太新了），我之前使用的 pyenv。不过还是建议用 /usr/bin/python， 我已经更新了 v.1.4.1 = 来调用 /usr/bin/python，你可以再下载下来试一下。有问题再说。

**Comment by Aerdax** [comment]
> Homebrew 的 Python 之前确实有点问题 （可能是因为版本太新了），我之前使用的 pyenv。不过还是建议用 /usr/bin/python， 我已经更新了 v.1.4.1 = 来调用 /usr/bin/python，你可以再下载下来试一下。有问题再说。

没有问题了，感谢大佬！

**Comment by yinan-c** [comment]
嗯，那就好！
